***REMOVED***
***REMOVED***
***REMOVED***

***REMOVED***
    "email": "john.barnes1983@outlook.com",
    "password": "pass"
***REMOVED***

***REMOVED***
***REMOVED***
***REMOVED***
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MjkyOTY1MDEsImV4cCI6MTYyOTQ2OTMwMSwiYXVkIjoiNjExZDE3NjVhOTcyYzA3NDFiNzRlNTc4IiwiaXNzIjoiaHR0cHM6Ly93d3cubXl3ZWJzaXRlLmNvbSJ9.D_LqmDKQ6NNLNnzOiVYbOLRdf7erI_BEsSJFyVgQmHQ

***REMOVED***
    "content": "hey there!", 
    "imageUri": "http://google.com/images"
***REMOVED***

***REMOVED***
PATCH  http://localhost:4003/api/posts/611d19f4810a7ab8981c74ac
***REMOVED***
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MjkyOTY1MDEsImV4cCI6MTYyOTQ2OTMwMSwiYXVkIjoiNjExZDE3NjVhOTcyYzA3NDFiNzRlNTc4IiwiaXNzIjoiaHR0cHM6Ly93d3cubXl3ZWJzaXRlLmNvbSJ9.D_LqmDKQ6NNLNnzOiVYbOLRdf7erI_BEsSJFyVgQmHQ

***REMOVED***
    "content": "hit 'em up"
***REMOVED***

***REMOVED***
GET  http://localhost:4003/api/posts/611d19f4810a7ab8981c74ac
***REMOVED***
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MjkyOTY1MDEsImV4cCI6MTYyOTQ2OTMwMSwiYXVkIjoiNjExZDE3NjVhOTcyYzA3NDFiNzRlNTc4IiwiaXNzIjoiaHR0cHM6Ly93d3cubXl3ZWJzaXRlLmNvbSJ9.D_LqmDKQ6NNLNnzOiVYbOLRdf7erI_BEsSJFyVgQmHQ

***REMOVED***
POST  http://localhost:4003/api/posts/611d19f4810a7ab8981c74ac/comment/new
***REMOVED***
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MjkyOTY1MDEsImV4cCI6MTYyOTQ2OTMwMSwiYXVkIjoiNjExZDE3NjVhOTcyYzA3NDFiNzRlNTc4IiwiaXNzIjoiaHR0cHM6Ly93d3cubXl3ZWJzaXRlLmNvbSJ9.D_LqmDKQ6NNLNnzOiVYbOLRdf7erI_BEsSJFyVgQmHQ

***REMOVED***
    "comment":"yooooo!"
***REMOVED***

***REMOVED***
GET  http://localhost:4003/api/posts/611d19f4810a7ab8981c74ac/comments
***REMOVED***
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MjkyOTY1MDEsImV4cCI6MTYyOTQ2OTMwMSwiYXVkIjoiNjExZDE3NjVhOTcyYzA3NDFiNzRlNTc4IiwiaXNzIjoiaHR0cHM6Ly93d3cubXl3ZWJzaXRlLmNvbSJ9.D_LqmDKQ6NNLNnzOiVYbOLRdf7erI_BEsSJFyVgQmHQ

***REMOVED***
GET  http://localhost:4003/api/posts/users/611d1765a972c0741b74e578/fetchPosts
***REMOVED***
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MjkyOTY1MDEsImV4cCI6MTYyOTQ2OTMwMSwiYXVkIjoiNjExZDE3NjVhOTcyYzA3NDFiNzRlNTc4IiwiaXNzIjoiaHR0cHM6Ly93d3cubXl3ZWJzaXRlLmNvbSJ9.D_LqmDKQ6NNLNnzOiVYbOLRdf7erI_BEsSJFyVgQmHQ


***REMOVED***
GET  http://localhost:4003/api/posts/users/611d1765a972c0741b74e578/fetchLikedPosts
***REMOVED***
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MjkyOTY1MDEsImV4cCI6MTYyOTQ2OTMwMSwiYXVkIjoiNjExZDE3NjVhOTcyYzA3NDFiNzRlNTc4IiwiaXNzIjoiaHR0cHM6Ly93d3cubXl3ZWJzaXRlLmNvbSJ9.D_LqmDKQ6NNLNnzOiVYbOLRdf7erI_BEsSJFyVgQmHQ

***REMOVED***
GET  http://localhost:4003/api/posts/611d19f4810a7ab8981c74ac/likes
***REMOVED***
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MjkyOTY1MDEsImV4cCI6MTYyOTQ2OTMwMSwiYXVkIjoiNjExZDE3NjVhOTcyYzA3NDFiNzRlNTc4IiwiaXNzIjoiaHR0cHM6Ly93d3cubXl3ZWJzaXRlLmNvbSJ9.D_LqmDKQ6NNLNnzOiVYbOLRdf7erI_BEsSJFyVgQmHQ

***REMOVED***
POST  http://localhost:4003/api/posts/611d19f4810a7ab8981c74ac/like
***REMOVED***
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MjkyOTY1MDEsImV4cCI6MTYyOTQ2OTMwMSwiYXVkIjoiNjExZDE3NjVhOTcyYzA3NDFiNzRlNTc4IiwiaXNzIjoiaHR0cHM6Ly93d3cubXl3ZWJzaXRlLmNvbSJ9.D_LqmDKQ6NNLNnzOiVYbOLRdf7erI_BEsSJFyVgQmHQ

***REMOVED***
DELETE  http://localhost:4003/api/posts/611d19f4810a7ab8981c74ac/unlike
***REMOVED***
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MjkyOTY1MDEsImV4cCI6MTYyOTQ2OTMwMSwiYXVkIjoiNjExZDE3NjVhOTcyYzA3NDFiNzRlNTc4IiwiaXNzIjoiaHR0cHM6Ly93d3cubXl3ZWJzaXRlLmNvbSJ9.D_LqmDKQ6NNLNnzOiVYbOLRdf7erI_BEsSJFyVgQmHQ

