### login via the auth service for access and refresh token pairs
POST  http://localhost:4000/api/auth/login
content-type: application/json

{
    "email": "si3iid@gmail.com",
    "password": "pass"
}


### homepage
GET http://localhost:4001
content-type: application/json

### create chatroom
POST  http://localhost:4001/api/chats/new
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MjkyOTE2NzUsImV4cCI6MTYyOTQ2NDQ3NSwiYXVkIjoiNjExZDAxM2Y1MzEwNDU2NGU4OGUwZGJmIiwiaXNzIjoiaHR0cHM6Ly93d3cubXl3ZWJzaXRlLmNvbSJ9.vaF1zqAot2t4RonJuziP0h91uPO3TKLUdJBJgHhogCY

{
    "email": "si3iid@icloud.com"
}

### fetch chatroom data by id
GET  http://localhost:4001/api/chats/611d06c05230a37396fa7281
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MjkyOTE2NzUsImV4cCI6MTYyOTQ2NDQ3NSwiYXVkIjoiNjExZDAxM2Y1MzEwNDU2NGU4OGUwZGJmIiwiaXNzIjoiaHR0cHM6Ly93d3cubXl3ZWJzaXRlLmNvbSJ9.vaF1zqAot2t4RonJuziP0h91uPO3TKLUdJBJgHhogCY

### update chatroom
PATCH  http://localhost:4001/api/chats/611d06c05230a37396fa7281
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MjkyOTE2NzUsImV4cCI6MTYyOTQ2NDQ3NSwiYXVkIjoiNjExZDAxM2Y1MzEwNDU2NGU4OGUwZGJmIiwiaXNzIjoiaHR0cHM6Ly93d3cubXl3ZWJzaXRlLmNvbSJ9.vaF1zqAot2t4RonJuziP0h91uPO3TKLUdJBJgHhogCY

{
    "name": "team",
    "isGroupChat": true
}

### fetch user chat rooms
GET  http://localhost:4001/api/chats/users/611a55e3a72b7c92878afb34/chatrooms
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MjkyOTE2NzUsImV4cCI6MTYyOTQ2NDQ3NSwiYXVkIjoiNjExZDAxM2Y1MzEwNDU2NGU4OGUwZGJmIiwiaXNzIjoiaHR0cHM6Ly93d3cubXl3ZWJzaXRlLmNvbSJ9.vaF1zqAot2t4RonJuziP0h91uPO3TKLUdJBJgHhogCY

### fetch chatroom recipients
GET  http://localhost:4001/api/chats/611d06c05230a37396fa7281/users
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MjkyOTE2NzUsImV4cCI6MTYyOTQ2NDQ3NSwiYXVkIjoiNjExZDAxM2Y1MzEwNDU2NGU4OGUwZGJmIiwiaXNzIjoiaHR0cHM6Ly93d3cubXl3ZWJzaXRlLmNvbSJ9.vaF1zqAot2t4RonJuziP0h91uPO3TKLUdJBJgHhogCY

### create new message
POST  http://localhost:4001/api/chats/611d06c05230a37396fa7281/messages/new
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MjkyOTE2NzUsImV4cCI6MTYyOTQ2NDQ3NSwiYXVkIjoiNjExZDAxM2Y1MzEwNDU2NGU4OGUwZGJmIiwiaXNzIjoiaHR0cHM6Ly93d3cubXl3ZWJzaXRlLmNvbSJ9.vaF1zqAot2t4RonJuziP0h91uPO3TKLUdJBJgHhogCY

{
    "chatRoomId":"610529411f691f0b3b1193e8",
    "content":"yooo",
    "imageUri":"http://google.com"
}

### fetch chatroom messages
GET  http://localhost:4001/api/chats/611d06c05230a37396fa7281/messages
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MjkyOTE2NzUsImV4cCI6MTYyOTQ2NDQ3NSwiYXVkIjoiNjExZDAxM2Y1MzEwNDU2NGU4OGUwZGJmIiwiaXNzIjoiaHR0cHM6Ly93d3cubXl3ZWJzaXRlLmNvbSJ9.vaF1zqAot2t4RonJuziP0h91uPO3TKLUdJBJgHhogCY
