### login via the auth service for access and refresh token pairs
POST  http://localhost:4000/login
content-type: application/json

{
    "email": "john.barnes1983@outlook.com",
    "password": "pass"
}

### homepage
GET http://localhost:4004
content-type: application/json

### create profile
POST  http://localhost:4004/api/profiles/new
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MjkyOTkwMDAsImV4cCI6MTYyOTQ3MTgwMCwiYXVkIjoiNjExZDIxMzhhOTcyYzA3NDFiNzRlNTdjIiwiaXNzIjoiaHR0cHM6Ly93d3cubXl3ZWJzaXRlLmNvbSJ9.6upFoNEgRZ6wm8ecxFbgGJxSDrlgE0he4j63qPIsKgw

{
    "username":"si3iid",
    "name":"said",
    "profilePicture":"http://google.com/p/si3iid",
    "bio":""
}

### fetch profile data by userId
GET  http://localhost:4004/api/profiles/users/611d2138a972c0741b74e57c
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MjkyOTkwMDAsImV4cCI6MTYyOTQ3MTgwMCwiYXVkIjoiNjExZDIxMzhhOTcyYzA3NDFiNzRlNTdjIiwiaXNzIjoiaHR0cHM6Ly93d3cubXl3ZWJzaXRlLmNvbSJ9.6upFoNEgRZ6wm8ecxFbgGJxSDrlgE0he4j63qPIsKgw

### fetch profile data by username
GET  http://localhost:4004/api/profiles/user?username=si3iid
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MjkyOTkwMDAsImV4cCI6MTYyOTQ3MTgwMCwiYXVkIjoiNjExZDIxMzhhOTcyYzA3NDFiNzRlNTdjIiwiaXNzIjoiaHR0cHM6Ly93d3cubXl3ZWJzaXRlLmNvbSJ9.6upFoNEgRZ6wm8ecxFbgGJxSDrlgE0he4j63qPIsKgw

### fetch profile data by name
GET  http://localhost:4004/api/profiles/user?name=said
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MjkyOTkwMDAsImV4cCI6MTYyOTQ3MTgwMCwiYXVkIjoiNjExZDIxMzhhOTcyYzA3NDFiNzRlNTdjIiwiaXNzIjoiaHR0cHM6Ly93d3cubXl3ZWJzaXRlLmNvbSJ9.6upFoNEgRZ6wm8ecxFbgGJxSDrlgE0he4j63qPIsKgw

### update profile
PATCH  http://localhost:4004/api/profiles/update
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MjkyOTkwMDAsImV4cCI6MTYyOTQ3MTgwMCwiYXVkIjoiNjExZDIxMzhhOTcyYzA3NDFiNzRlNTdjIiwiaXNzIjoiaHR0cHM6Ly93d3cubXl3ZWJzaXRlLmNvbSJ9.6upFoNEgRZ6wm8ecxFbgGJxSDrlgE0he4j63qPIsKgw

{
    "username":"si3iid",
    "name":"Said",
    "profilePicture":"http://google.com/p/bond007"
}