### login via the auth service for access and refresh token pairs
POST  http://localhost:4000/api/auth/login
content-type: application/json

{
    "email": "john.barnes1983@outlook.com",
    "password": "pass"
}

### create post
POST  http://localhost:4003/api/posts/new
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MzAxNTc2ODYsImV4cCI6MTYzMDMzMDQ4NiwiYXVkIjoiNjEyYTNiNzYyZThjMzIyODllNjM5Y2VlIiwiaXNzIjoiaHR0cHM6Ly93d3cubXl3ZWJzaXRlLmNvbSJ9.1VrgcHA-d65YU9vqWNE38ekm0lw1sjk8BgzfuHNy0VQ

{
    "caption": "hey there!", 
    "imageUri": "http://google.com/images"
}

### update post
PATCH  http://localhost:4003/api/posts/612a3c48da323d28b69b73fd
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MzAxNTc2ODYsImV4cCI6MTYzMDMzMDQ4NiwiYXVkIjoiNjEyYTNiNzYyZThjMzIyODllNjM5Y2VlIiwiaXNzIjoiaHR0cHM6Ly93d3cubXl3ZWJzaXRlLmNvbSJ9.1VrgcHA-d65YU9vqWNE38ekm0lw1sjk8BgzfuHNy0VQ

{
    "imageUri":"http://google.com",
    "caption": "hit 'em up"
}

### fetch feed
GET  http://localhost:4003/api/posts/feed/all
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2Mjk3MjIwMTQsImV4cCI6MTYyOTg5NDgxNCwiYXVkIjoiNjExZDBhYmRhOTcyYzA3NDFiNzRlNTc0IiwiaXNzIjoiaHR0cHM6Ly93d3cubXl3ZWJzaXRlLmNvbSJ9.5TFXB2uDlDZto-MCF2NGrjJwMGnJ3kcT5oCuT5FT5ZM


### fetch post data by id
GET  http://localhost:4003/api/posts/611d19f4810a7ab8981c74ac
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MzAxNTc2ODYsImV4cCI6MTYzMDMzMDQ4NiwiYXVkIjoiNjEyYTNiNzYyZThjMzIyODllNjM5Y2VlIiwiaXNzIjoiaHR0cHM6Ly93d3cubXl3ZWJzaXRlLmNvbSJ9.1VrgcHA-d65YU9vqWNE38ekm0lw1sjk8BgzfuHNy0VQ

### create comment on a post by id
POST  http://localhost:4003/api/posts/611d19f4810a7ab8981c74ac/comment/new
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MzAxNTc2ODYsImV4cCI6MTYzMDMzMDQ4NiwiYXVkIjoiNjEyYTNiNzYyZThjMzIyODllNjM5Y2VlIiwiaXNzIjoiaHR0cHM6Ly93d3cubXl3ZWJzaXRlLmNvbSJ9.1VrgcHA-d65YU9vqWNE38ekm0lw1sjk8BgzfuHNy0VQ

{
    "comment":"yooooo!"
}

### fetch posts comments
GET  http://localhost:4003/api/posts/611d19f4810a7ab8981c74ac/comments
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MzAxNTc2ODYsImV4cCI6MTYzMDMzMDQ4NiwiYXVkIjoiNjEyYTNiNzYyZThjMzIyODllNjM5Y2VlIiwiaXNzIjoiaHR0cHM6Ly93d3cubXl3ZWJzaXRlLmNvbSJ9.1VrgcHA-d65YU9vqWNE38ekm0lw1sjk8BgzfuHNy0VQ

### fetch user posts
GET  http://localhost:4003/api/posts/users/612a0fe669908c1d75311190/fetchPosts
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MzAxNTc2ODYsImV4cCI6MTYzMDMzMDQ4NiwiYXVkIjoiNjEyYTNiNzYyZThjMzIyODllNjM5Y2VlIiwiaXNzIjoiaHR0cHM6Ly93d3cubXl3ZWJzaXRlLmNvbSJ9.1VrgcHA-d65YU9vqWNE38ekm0lw1sjk8BgzfuHNy0VQ


### fetch posts liked by user
GET  http://localhost:4003/api/posts/users/611d1765a972c0741b74e578/fetchLikedPosts
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MzAxNTc2ODYsImV4cCI6MTYzMDMzMDQ4NiwiYXVkIjoiNjEyYTNiNzYyZThjMzIyODllNjM5Y2VlIiwiaXNzIjoiaHR0cHM6Ly93d3cubXl3ZWJzaXRlLmNvbSJ9.1VrgcHA-d65YU9vqWNE38ekm0lw1sjk8BgzfuHNy0VQ

### fetch likes for post
GET  http://localhost:4003/api/posts/611d19f4810a7ab8981c74ac/likes
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MzAxNTc2ODYsImV4cCI6MTYzMDMzMDQ4NiwiYXVkIjoiNjEyYTNiNzYyZThjMzIyODllNjM5Y2VlIiwiaXNzIjoiaHR0cHM6Ly93d3cubXl3ZWJzaXRlLmNvbSJ9.1VrgcHA-d65YU9vqWNE38ekm0lw1sjk8BgzfuHNy0VQ

### like a post by id
POST  http://localhost:4003/api/posts/612a11bdb325112ace2254ba/like
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MzAxNTc2ODYsImV4cCI6MTYzMDMzMDQ4NiwiYXVkIjoiNjEyYTNiNzYyZThjMzIyODllNjM5Y2VlIiwiaXNzIjoiaHR0cHM6Ly93d3cubXl3ZWJzaXRlLmNvbSJ9.1VrgcHA-d65YU9vqWNE38ekm0lw1sjk8BgzfuHNy0VQ

### unlike a post by id
DELETE  http://localhost:4003/api/posts/612a11bdb325112ace2254ba/like
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MzAxNTc2ODYsImV4cCI6MTYzMDMzMDQ4NiwiYXVkIjoiNjEyYTNiNzYyZThjMzIyODllNjM5Y2VlIiwiaXNzIjoiaHR0cHM6Ly93d3cubXl3ZWJzaXRlLmNvbSJ9.1VrgcHA-d65YU9vqWNE38ekm0lw1sjk8BgzfuHNy0VQ

### bookmark a post by id
POST  http://localhost:4003/api/posts/612a11bdb325112ace2254ba/bookmark
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MzAxNTc2ODYsImV4cCI6MTYzMDMzMDQ4NiwiYXVkIjoiNjEyYTNiNzYyZThjMzIyODllNjM5Y2VlIiwiaXNzIjoiaHR0cHM6Ly93d3cubXl3ZWJzaXRlLmNvbSJ9.1VrgcHA-d65YU9vqWNE38ekm0lw1sjk8BgzfuHNy0VQ

### unbookmark post by id
DELETE  http://localhost:4003/api/posts/612a11bdb325112ace2254ba/bookmark
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MzAxNTc2ODYsImV4cCI6MTYzMDMzMDQ4NiwiYXVkIjoiNjEyYTNiNzYyZThjMzIyODllNjM5Y2VlIiwiaXNzIjoiaHR0cHM6Ly93d3cubXl3ZWJzaXRlLmNvbSJ9.1VrgcHA-d65YU9vqWNE38ekm0lw1sjk8BgzfuHNy0VQ

### fetch posts bookmarked by user
GET  http://localhost:4003/api/posts/bookmarks/me
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MzAxNTc2ODYsImV4cCI6MTYzMDMzMDQ4NiwiYXVkIjoiNjEyYTNiNzYyZThjMzIyODllNjM5Y2VlIiwiaXNzIjoiaHR0cHM6Ly93d3cubXl3ZWJzaXRlLmNvbSJ9.1VrgcHA-d65YU9vqWNE38ekm0lw1sjk8BgzfuHNy0VQ