### login via the auth service for access and refresh token pairs
POST  http://localhost:4000/login
content-type: application/json

{
    "email": "si3iid@gmail.com",
    "password": "pass"
}


### homepage
GET http://localhost:4001
content-type: application/json

### create chatroom
POST  http://localhost:4001/chatrooms/new
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2Mjc4MTQ3MzEsImV4cCI6MTYyNzgxODMzMSwiYXVkIjoiNjEwM2MxNzNkNmRkZGFmMzdmOTFlYjNhIiwiaXNzIjoiaHR0cHM6Ly93d3cubXl3ZWJzaXRlLmNvbSJ9.IyBex8Kkh9Q6oe-8zwp5GoT2Y6JMOePN0xLcj2efoTI

{
    "email": "si3iid@gmail.com"
}

### fetch chatroom data by id
GET  http://localhost:4001/chatrooms/610529411f691f0b3b1193e8
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2Mjc4MTQ3MzEsImV4cCI6MTYyNzgxODMzMSwiYXVkIjoiNjEwM2MxNzNkNmRkZGFmMzdmOTFlYjNhIiwiaXNzIjoiaHR0cHM6Ly93d3cubXl3ZWJzaXRlLmNvbSJ9.IyBex8Kkh9Q6oe-8zwp5GoT2Y6JMOePN0xLcj2efoTI

### update chatroom
PATCH  http://localhost:4001/chatrooms/610529411f691f0b3b1193e8
content-type: application/json
authorization: Bearer Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2Mjc4MTQ3MzEsImV4cCI6MTYyNzgxODMzMSwiYXVkIjoiNjEwM2MxNzNkNmRkZGFmMzdmOTFlYjNhIiwiaXNzIjoiaHR0cHM6Ly93d3cubXl3ZWJzaXRlLmNvbSJ9.IyBex8Kkh9Q6oe-8zwp5GoT2Y6JMOePN0xLcj2efoTI

{
    "name": "team",
    "isGroupChat": true
}

### fetch user chat rooms
GET  http://localhost:4001/users/6103c9f800949ffa12ac1477/chatrooms
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2Mjc4MTQ3MzEsImV4cCI6MTYyNzgxODMzMSwiYXVkIjoiNjEwM2MxNzNkNmRkZGFmMzdmOTFlYjNhIiwiaXNzIjoiaHR0cHM6Ly93d3cubXl3ZWJzaXRlLmNvbSJ9.IyBex8Kkh9Q6oe-8zwp5GoT2Y6JMOePN0xLcj2efoTI

### fetch chatroom recipients
GET  http://localhost:4001/chatrooms/610529411f691f0b3b1193e8/users
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2Mjc4MTQ3MzEsImV4cCI6MTYyNzgxODMzMSwiYXVkIjoiNjEwM2MxNzNkNmRkZGFmMzdmOTFlYjNhIiwiaXNzIjoiaHR0cHM6Ly93d3cubXl3ZWJzaXRlLmNvbSJ9.IyBex8Kkh9Q6oe-8zwp5GoT2Y6JMOePN0xLcj2efoTI

### create new message
POST  http://localhost:4001/messages/new
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2Mjc4MTQ3MzEsImV4cCI6MTYyNzgxODMzMSwiYXVkIjoiNjEwM2MxNzNkNmRkZGFmMzdmOTFlYjNhIiwiaXNzIjoiaHR0cHM6Ly93d3cubXl3ZWJzaXRlLmNvbSJ9.IyBex8Kkh9Q6oe-8zwp5GoT2Y6JMOePN0xLcj2efoTI

{
    "chatRoomId":"610529411f691f0b3b1193e8",
    "content":"yooo",
    "imageUri":"http://google.com"
}

### fetch chatroom messages
GET  http://localhost:4001/chatrooms/610529411f691f0b3b1193e8/messages
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2Mjc4MTQ3MzEsImV4cCI6MTYyNzgxODMzMSwiYXVkIjoiNjEwM2MxNzNkNmRkZGFmMzdmOTFlYjNhIiwiaXNzIjoiaHR0cHM6Ly93d3cubXl3ZWJzaXRlLmNvbSJ9.IyBex8Kkh9Q6oe-8zwp5GoT2Y6JMOePN0xLcj2efoTI
