***REMOVED***
***REMOVED***
***REMOVED***

***REMOVED***
    "email": "si3iid@gmail.com",
    "password": "pass"
***REMOVED***


### homepage
GET http://localhost:4001
***REMOVED***

### create chatroom
POST  http://localhost:4001/api/chats/new
***REMOVED***
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MjkyOTE2NzUsImV4cCI6MTYyOTQ2NDQ3NSwiYXVkIjoiNjExZDAxM2Y1MzEwNDU2NGU4OGUwZGJmIiwiaXNzIjoiaHR0cHM6Ly93d3cubXl3ZWJzaXRlLmNvbSJ9.vaF1zqAot2t4RonJuziP0h91uPO3TKLUdJBJgHhogCY

***REMOVED***
    "email": "si3iid@icloud.com"
***REMOVED***

### fetch chatroom data by id
GET  http://localhost:4001/api/chats/611d06c05230a37396fa7281
***REMOVED***
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MjkyOTE2NzUsImV4cCI6MTYyOTQ2NDQ3NSwiYXVkIjoiNjExZDAxM2Y1MzEwNDU2NGU4OGUwZGJmIiwiaXNzIjoiaHR0cHM6Ly93d3cubXl3ZWJzaXRlLmNvbSJ9.vaF1zqAot2t4RonJuziP0h91uPO3TKLUdJBJgHhogCY

### update chatroom
PATCH  http://localhost:4001/api/chats/611d06c05230a37396fa7281
***REMOVED***
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MjkyOTE2NzUsImV4cCI6MTYyOTQ2NDQ3NSwiYXVkIjoiNjExZDAxM2Y1MzEwNDU2NGU4OGUwZGJmIiwiaXNzIjoiaHR0cHM6Ly93d3cubXl3ZWJzaXRlLmNvbSJ9.vaF1zqAot2t4RonJuziP0h91uPO3TKLUdJBJgHhogCY

***REMOVED***
    "name": "team",
    "isGroupChat": true
***REMOVED***

### fetch user chat rooms
GET  http://localhost:4001/api/chats/users/611a55e3a72b7c92878afb34/chatrooms
***REMOVED***
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MjkyOTE2NzUsImV4cCI6MTYyOTQ2NDQ3NSwiYXVkIjoiNjExZDAxM2Y1MzEwNDU2NGU4OGUwZGJmIiwiaXNzIjoiaHR0cHM6Ly93d3cubXl3ZWJzaXRlLmNvbSJ9.vaF1zqAot2t4RonJuziP0h91uPO3TKLUdJBJgHhogCY

### fetch chatroom recipients
GET  http://localhost:4001/api/chats/611d06c05230a37396fa7281/users
***REMOVED***
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MjkyOTE2NzUsImV4cCI6MTYyOTQ2NDQ3NSwiYXVkIjoiNjExZDAxM2Y1MzEwNDU2NGU4OGUwZGJmIiwiaXNzIjoiaHR0cHM6Ly93d3cubXl3ZWJzaXRlLmNvbSJ9.vaF1zqAot2t4RonJuziP0h91uPO3TKLUdJBJgHhogCY

### create new message
POST  http://localhost:4001/api/chats/611d06c05230a37396fa7281/messages/new
***REMOVED***
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MjkyOTE2NzUsImV4cCI6MTYyOTQ2NDQ3NSwiYXVkIjoiNjExZDAxM2Y1MzEwNDU2NGU4OGUwZGJmIiwiaXNzIjoiaHR0cHM6Ly93d3cubXl3ZWJzaXRlLmNvbSJ9.vaF1zqAot2t4RonJuziP0h91uPO3TKLUdJBJgHhogCY

***REMOVED***
    "chatRoomId":"610529411f691f0b3b1193e8",
    "content":"yooo",
    "imageUri":"http://google.com"
***REMOVED***

### fetch chatroom messages
GET  http://localhost:4001/api/chats/611d06c05230a37396fa7281/messages
***REMOVED***
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MjkyOTE2NzUsImV4cCI6MTYyOTQ2NDQ3NSwiYXVkIjoiNjExZDAxM2Y1MzEwNDU2NGU4OGUwZGJmIiwiaXNzIjoiaHR0cHM6Ly93d3cubXl3ZWJzaXRlLmNvbSJ9.vaF1zqAot2t4RonJuziP0h91uPO3TKLUdJBJgHhogCY
