user nginx;
worker_processes 1;

error_log   /var/log/nginx/error.log warn;
pid         /var/run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    upstream auth_backend {
        server auth-service-1:4000
        server auth-service-2:4001
    }

    # upstream backend {
    #     server chat-service:
    # }

    # upstream backend {
    #     server email-service:
    # }

    server {
        location / {
            proxy_pass http://auth_backend;
        }
    }
}