***REMOVED***
POST  http://localhost:4000/login
***REMOVED***

***REMOVED***
    "email": "john.barnes1983@outlook.com",
    "password": "pass"
***REMOVED***

### homepage
GET http://localhost:4004
***REMOVED***

### create profile
POST  http://localhost:4004/api/profiles/new
***REMOVED***
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MjkyOTkwMDAsImV4cCI6MTYyOTQ3MTgwMCwiYXVkIjoiNjExZDIxMzhhOTcyYzA3NDFiNzRlNTdjIiwiaXNzIjoiaHR0cHM6Ly93d3cubXl3ZWJzaXRlLmNvbSJ9.6upFoNEgRZ6wm8ecxFbgGJxSDrlgE0he4j63qPIsKgw

***REMOVED***
    "username":"si3iid",
    "name":"said",
    "profilePicture":"http://google.com/p/si3iid",
    "bio":""
***REMOVED***

### fetch profile data by userId
GET  http://localhost:4004/api/profiles/users/611d2138a972c0741b74e57c
***REMOVED***
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MjkyOTkwMDAsImV4cCI6MTYyOTQ3MTgwMCwiYXVkIjoiNjExZDIxMzhhOTcyYzA3NDFiNzRlNTdjIiwiaXNzIjoiaHR0cHM6Ly93d3cubXl3ZWJzaXRlLmNvbSJ9.6upFoNEgRZ6wm8ecxFbgGJxSDrlgE0he4j63qPIsKgw

### fetch profile data by username
GET  http://localhost:4004/api/profiles/user?username=si3iid
***REMOVED***
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MjkyOTkwMDAsImV4cCI6MTYyOTQ3MTgwMCwiYXVkIjoiNjExZDIxMzhhOTcyYzA3NDFiNzRlNTdjIiwiaXNzIjoiaHR0cHM6Ly93d3cubXl3ZWJzaXRlLmNvbSJ9.6upFoNEgRZ6wm8ecxFbgGJxSDrlgE0he4j63qPIsKgw

### fetch profile data by name
GET  http://localhost:4004/api/profiles/user?name=said
***REMOVED***
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MjkyOTkwMDAsImV4cCI6MTYyOTQ3MTgwMCwiYXVkIjoiNjExZDIxMzhhOTcyYzA3NDFiNzRlNTdjIiwiaXNzIjoiaHR0cHM6Ly93d3cubXl3ZWJzaXRlLmNvbSJ9.6upFoNEgRZ6wm8ecxFbgGJxSDrlgE0he4j63qPIsKgw

### update profile
PATCH  http://localhost:4004/api/profiles/update
***REMOVED***
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MjkyOTkwMDAsImV4cCI6MTYyOTQ3MTgwMCwiYXVkIjoiNjExZDIxMzhhOTcyYzA3NDFiNzRlNTdjIiwiaXNzIjoiaHR0cHM6Ly93d3cubXl3ZWJzaXRlLmNvbSJ9.6upFoNEgRZ6wm8ecxFbgGJxSDrlgE0he4j63qPIsKgw

***REMOVED***
    "username":"si3iid",
    "name":"Said",
    "profilePicture":"http://google.com/p/bond007"
***REMOVED***