***REMOVED***
POST  http://localhost:4000/login
***REMOVED***

***REMOVED***
    "email": "john.barnes1983@outlook.com",
    "password": "pass"
***REMOVED***

### homepage
GET http://localhost:4004
***REMOVED***

### create profile
POST  http://localhost:4004/profiles/new
***REMOVED***
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MjkxMTc4NzEsImV4cCI6MTYyOTI5MDY3MSwiYXVkIjoiNjExYTU1ZTNhNzJiN2M5Mjg3OGFmYjM0IiwiaXNzIjoiaHR0cHM6Ly93d3cubXl3ZWJzaXRlLmNvbSJ9.NJju0ijPtt-mKbj9SJ98lMrCr1XqX9GjnGJGAVMi3kA

***REMOVED***
    "username":"bond007",
    "name":"bond",
    "profilePicture":"http://google.com/p/si3iid",
    "bio":"bond, james bond!"
***REMOVED***

### fetch profile data by userId
GET  http://localhost:4004/profiles/users/611a55e3a72b7c92878afb34
***REMOVED***
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MjkxMTc4NzEsImV4cCI6MTYyOTI5MDY3MSwiYXVkIjoiNjExYTU1ZTNhNzJiN2M5Mjg3OGFmYjM0IiwiaXNzIjoiaHR0cHM6Ly93d3cubXl3ZWJzaXRlLmNvbSJ9.NJju0ijPtt-mKbj9SJ98lMrCr1XqX9GjnGJGAVMi3kA

### fetch profile data by username
GET  http://localhost:4004/profiles/user?username=jackson
***REMOVED***
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MjkxMTc4NzEsImV4cCI6MTYyOTI5MDY3MSwiYXVkIjoiNjExYTU1ZTNhNzJiN2M5Mjg3OGFmYjM0IiwiaXNzIjoiaHR0cHM6Ly93d3cubXl3ZWJzaXRlLmNvbSJ9.NJju0ijPtt-mKbj9SJ98lMrCr1XqX9GjnGJGAVMi3kA

### fetch profile data by name
GET  http://localhost:4004/profiles/user?name=jackson
***REMOVED***
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MjkxMTc4NzEsImV4cCI6MTYyOTI5MDY3MSwiYXVkIjoiNjExYTU1ZTNhNzJiN2M5Mjg3OGFmYjM0IiwiaXNzIjoiaHR0cHM6Ly93d3cubXl3ZWJzaXRlLmNvbSJ9.NJju0ijPtt-mKbj9SJ98lMrCr1XqX9GjnGJGAVMi3kA

### update profile
PATCH  http://localhost:4004/profiles/update
***REMOVED***
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MjkxMTc4NzEsImV4cCI6MTYyOTI5MDY3MSwiYXVkIjoiNjExYTU1ZTNhNzJiN2M5Mjg3OGFmYjM0IiwiaXNzIjoiaHR0cHM6Ly93d3cubXl3ZWJzaXRlLmNvbSJ9.NJju0ijPtt-mKbj9SJ98lMrCr1XqX9GjnGJGAVMi3kA

***REMOVED***
    "username":"bond007",
    "name":"bond",
    "profilePicture":"http://google.com/p/bond007"
***REMOVED***

***REMOVED***
POST  http://localhost:4004/posts/610faa0f1caa5eb319e7cf3b/comment/new
***REMOVED***
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MjkxMTc4NzEsImV4cCI6MTYyOTI5MDY3MSwiYXVkIjoiNjExYTU1ZTNhNzJiN2M5Mjg3OGFmYjM0IiwiaXNzIjoiaHR0cHM6Ly93d3cubXl3ZWJzaXRlLmNvbSJ9.NJju0ijPtt-mKbj9SJ98lMrCr1XqX9GjnGJGAVMi3kA

***REMOVED***
    "comment":"hahaha"
***REMOVED***

***REMOVED***
GET  http://localhost:4004/posts/610faa0f1caa5eb319e7cf3b/comments
***REMOVED***
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MjkxMTc4NzEsImV4cCI6MTYyOTI5MDY3MSwiYXVkIjoiNjExYTU1ZTNhNzJiN2M5Mjg3OGFmYjM0IiwiaXNzIjoiaHR0cHM6Ly93d3cubXl3ZWJzaXRlLmNvbSJ9.NJju0ijPtt-mKbj9SJ98lMrCr1XqX9GjnGJGAVMi3kA

***REMOVED***
GET  http://localhost:4004/users/610d45731fbb6776fcc10dc6/posts
***REMOVED***
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MjkxMTc4NzEsImV4cCI6MTYyOTI5MDY3MSwiYXVkIjoiNjExYTU1ZTNhNzJiN2M5Mjg3OGFmYjM0IiwiaXNzIjoiaHR0cHM6Ly93d3cubXl3ZWJzaXRlLmNvbSJ9.NJju0ijPtt-mKbj9SJ98lMrCr1XqX9GjnGJGAVMi3kA


### fetch posts liked by auth user
GET  http://localhost:4004/posts-likes
***REMOVED***
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MjkxMTc4NzEsImV4cCI6MTYyOTI5MDY3MSwiYXVkIjoiNjExYTU1ZTNhNzJiN2M5Mjg3OGFmYjM0IiwiaXNzIjoiaHR0cHM6Ly93d3cubXl3ZWJzaXRlLmNvbSJ9.NJju0ijPtt-mKbj9SJ98lMrCr1XqX9GjnGJGAVMi3kA

***REMOVED***
GET  http://localhost:4004/posts/610faa0f1caa5eb319e7cf3b/likes
***REMOVED***
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MjkxMTc4NzEsImV4cCI6MTYyOTI5MDY3MSwiYXVkIjoiNjExYTU1ZTNhNzJiN2M5Mjg3OGFmYjM0IiwiaXNzIjoiaHR0cHM6Ly93d3cubXl3ZWJzaXRlLmNvbSJ9.NJju0ijPtt-mKbj9SJ98lMrCr1XqX9GjnGJGAVMi3kA

***REMOVED***
POST  http://localhost:4004/posts/610faa0f1caa5eb319e7cf3b/like
***REMOVED***
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MjkxMTc4NzEsImV4cCI6MTYyOTI5MDY3MSwiYXVkIjoiNjExYTU1ZTNhNzJiN2M5Mjg3OGFmYjM0IiwiaXNzIjoiaHR0cHM6Ly93d3cubXl3ZWJzaXRlLmNvbSJ9.NJju0ijPtt-mKbj9SJ98lMrCr1XqX9GjnGJGAVMi3kA

***REMOVED***
DELETE  http://localhost:4004/posts/610faa241caa5eb319e7cf3d/unlike
***REMOVED***
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MjkxMTc4NzEsImV4cCI6MTYyOTI5MDY3MSwiYXVkIjoiNjExYTU1ZTNhNzJiN2M5Mjg3OGFmYjM0IiwiaXNzIjoiaHR0cHM6Ly93d3cubXl3ZWJzaXRlLmNvbSJ9.NJju0ijPtt-mKbj9SJ98lMrCr1XqX9GjnGJGAVMi3kA

